services:
  db:
    image: postgres
    container_name: gobank
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gobank
    volumes:
      - gobank:/data/postgres

volumes:
  gobank:
    driver: local
